Sensors:          # Expected sensors in the database
  A_x:    # Sensor 1 name
    features:     # Features configuration
      wavPowers:    off                          # Wavelet powers
      mean:         off                          # Mean value
      rms:          off                          # Root mean square
      peak:         off                          # Peak to peak value
      std:          off                          # Standard deviation
      skew:         off                          # Skewness
      kurt:         off                          # Kurtosis
  A_y:    # Sensor 2 name
    features:     # Features configuration
      wavPowers:    off                          # Wavelet powers
      mean:         off                          # Mean value
      rms:          off                          # Root mean square
      peak:         off                          # Peak to peak value
      std:          off                          # Standard deviation
      skew:         off                          # Skewness
      kurt:         off                          # Kurtosis
  A_z:    # Sensor 3 name
    features:     # Features configuration
      wavPowers:    on                          # Wavelet powers
      mean:         on                          # Mean value
      rms:          on                          # Root mean square
      peak:         on                          # Peak to peak value
      std:          on                          # Standard deviation
      skew:         on                          # Skewness
      kurt:         on                          # Kurtosis
wavelet:           # Wavelet packet reasform configuration
  type:               db10                        # Type of wavelet to use
  mode:               symmetric                   # Mode of the packet transform
  maxlevel:           6                           # Max level -> num of features = 2^level

miscellanea:
  logpath:            logs/demo.log        # Path to the logs